### ISSUE TITLE
Video description is left untranslated for videos selected after the initial YouTube page load

### ISSUE THREAD

**Issue by artisticfox8** [zpix1/yt-anti-translate#9] opened 2022-01-08 11:40 UTC
Tested in Chrome
Steps to reproduce:

1. Go to a video with a translated title, for example Pewdipie
2. Open Developer tools
2. Change YouTube language to Russian (the page reloads)
3. Paste `ytInitialPlayerResponse.videoDetails.shortDescription` in the Console
4. The description matches the English video description (good)
5. Cut the `ytInitialPlayerResponse.videoDetails.shortDescription` from the Console
3. Select a different video with a translated video title
4. Paste `ytInitialPlayerResponse.videoDetails.shortDescription` in the Console
5. The description returned from Console is the same one that we saw in step 3
6. Also the video description HTML text stayed Russian

Actual results:
the description and title of the first video are translated
the title of the second video is translated but the description of the second video is not translated
the `ytInitialPlayerResponse.videoDetails.shortDescription` variable still shows the first videos description. So that description is for a different video. 

Expected results:
the description and title of the both videos are translated

**Comment by artisticfox8** [comment] 2022-01-08 11:41
![bugreport screenshot 1](https://user-images.githubusercontent.com/77014769/148642798-66a47787-6711-4f8e-8bfb-bd65caa0c6d9.png)

**Comment by artisticfox8** [comment] 2022-01-08 11:42
![bugreport screenshot 2](https://user-images.githubusercontent.com/77014769/148642815-f2a2b89e-3815-43e1-ba25-af0ccfa7673d.png)

**Comment by artisticfox8** [comment] 2022-01-08 11:44
If I navigate further on a different video, the `ytInitialPlayerResponse.videoDetails.shortDescription` stays the same, it has the description of the first video.

**Comment by zpix1** [comment] 2022-01-08 17:12
Yeah, it's a know issue I don't know how to fix bc I haven't found any good source of original video description when next video is selected without page reload.
So description untranslation is pretty limited.

**Comment by zpix1** [comment] 2022-01-08 17:14
Well, this is even a duplicate of https://github.com/zpix1/yt-anti-translate/issues/2

**Closed by zpix1** 2022-01-08 17:14 UTC
Labels: bug
